export const defaultOptions = {
  controlPosition: 'right',
  append: false,
  actionButtons: [],
  controlOrder: [
    'autocomplete',
    'button',
    'checkbox',
    'checkbox-group',
    'date',
    'file',
    'header',
    'hidden',
    'paragraph',
    'number',
    'radio-group',
    'select',
    'flipswitch',
    'text',
    'textarea',
    'split'
  ],
  dataType: 'json',
  // Array of fields to disable
  disableFields: [],
  disabledAttrs: [],
  disabledActionButtons: [],
  disabledFieldButtons: {},
  editOnAdd: false,
  // Uneditable fields or other content you would like to appear
  // before and after regular fields:
  // array of objects with fields values
  // ex:
  // defaultFields: [{
  //   label: 'First Name',
  //   name: 'first-name',
  //   required: 'true',
  //   description: 'Your first name',
  //   type: 'text'
  // }, {
  //   label: 'Phone',
  //   name: 'phone',
  //   description: 'How can we reach you?',
  //   type: 'text'
  // }],
  defaultFields: [],
  fields: [],
  fieldRemoveWarn: false,
  inputSets: [],
  replaceFields: [],
  roles: {
    1: 'Administrator',
  },
  notify: {
    error: message => console.error(message),
    success: message => console.log(message),
    warning: message => console.warn(message),
  },
  onSave: (evt, formData) => null,
  onClearAll: () => null,
  prepend: false,
  sortableControls: false,
  stickyControls: {
    enable: true,
    offset: {
      top: 5,
      bottom: 'auto',
      right: 'auto',
    },
  },
  templates: {},
  showActionButtons: true,
  typeUserDisabledAttrs: {},
  typeUserAttrs: {},
  typeUserEvents: {},
  prefix: 'form-builder-',
}

export const styles = {
  btn: ['default', 'danger', 'info', 'primary', 'success', 'warning'],
}

export const defaultI18n = {
  location: 'https://formbuilder.online/assets/lang/',
  // langs: ['en-US'],
  langs: ['zh-CN', 'en-US'],

  preloaded: {
    'zh-CN': {
      addOption: '新增选项',
      allFieldsRemoved: '所有字段已删除',
      allowMultipleFiles: '允许用户上传多个文件',
      autocomplete: '自动完成',
      button: '按钮',
      cannotBeEmpty: '此字段不能为空',
      checkboxGroup: '复选框组',
      checkbox: '复选框',
      checkboxes: '复选框',
      className: 'CSS样式',
      clearAllMessage: '您确定要清空所有字段吗?',
      clear: '清除所有',
      close: '关闭',
      content: '内容',
      copy: '复制',
      copyButton: '&#43;',
      copyButtonTooltip: '复制',
      dateField: '日期字段',
      description: '帮助信息',
      descriptionField: '描述',
      devMode: '开发者模式',
      editNames: '编辑名称',
      editorTitle: '表单元素',
      editXML: '编辑XML',
      enableOther: '使用 &quot;其它&quot;',
      enableOtherMsg: '让用户指定选项',
      fieldNonEditable: '此字段不允许修改。',
      fieldRemoveWarning: '您确定要移除此字段吗?',
      file: '文件上传',
      fileUpload: '文件上传',
      fileUploadInTab: '文件上传单独显示',
      formUpdated: '表单已更新',
      getStarted: '请从右边拖拽控件。',
      header: '表头',
      split: '分割',
      hide: '隐藏域',
      hidden: '隐藏',
      inline: 'Inline',
      inlineDesc: 'Display {type} inline',
      label: '标签',
      labelEmpty: '标签字段不能为空',
      limitRole: '角色受限',
      mandatory: '强制填写',
      maxlength: '最大长度',
      minOptionMessage: '此字段至少需要选择两项',
      minSelectionRequired: '最少选择{min}项',
      multipleFiles: '多个文件',
      name: '名称',
      no: '否',
      noFieldsToClear: '没有需要清除的字段',
      number: '数字',
      money: '金额',
      off: '关',
      on: '开',
      option: '选项',
      options: '选项',
      optional: '可选',
      optionLabelPlaceholder: '标签',
      optionValuePlaceholder: '值',
      optionEmpty: '请输入选择',
      other: '其它',
      paragraph: '段落',
      placeholder: '占位符',
      'placeholder.value': '值',
      'placeholder.label': '标签',
      'placeholder.text': '请输入文字',
      'placeholder.textarea': '请输入文字',
      'placeholder.email': '请输入邮件地址',
      'placeholder.placeholder': '占位符',
      'placeholder.className': '以空格符分隔',
      'placeholder.password': '请输入密码',
      preview: '预览',
      radioGroup: '单选组',
      radio: '单选框',
      removeMessage: '移除控件',
      removeOption: '移除选项',
      remove: '&#215;',
      required: '必填',
      richText: '富文本框',
      roles: '访问',
      rows: 'Rows',
      save: '保存',
      selectOptions: '选项',
      select: '选择',
      selectColor: '选择颜色',
      selectionsMessage: '允许多选',
      size: '大小',
      'size.xs': '最小',
      'size.sm': '小',
      'size.m': '中',
      'size.lg': '大',
      style: '样式',
      'styles.btn.default': 'Default',
      'styles.btn.danger': 'Danger',
      'styles.btn.info': 'Info',
      'styles.btn.primary': 'Primary',
      'styles.btn.success': 'Success',
      'styles.btn.warning': 'Warning',
      subtype: '类型',
      text: '输入框',
      textArea: '文本框',
      toggle: '弹出提示',
      warning: '警告!',
      value: 'Value',
      viewJSON: '{  }',
      viewXML: '&lt;/&gt;',
      yes: '是',
      flipswitch: '开关',
      psbi: '用户id',
      psbm: '用户邮件地址',
      psbn: '用户名',
      bpid: '流程id',
      'datetime-local': '日期与时间',
      password: '密码'
    },
    'en-US': {
      addOption: 'Add Option +',
      allFieldsRemoved: 'All fields were removed.',
      allowMultipleFiles: 'Allow users to upload multiple files',
      autocomplete: 'Autocomplete',
      button: 'Button',
      cannotBeEmpty: 'This field cannot be empty',
      checkboxGroup: 'Checkbox Group',
      checkbox: 'Checkbox',
      checkboxes: 'Checkboxes',
      className: 'Class',
      clearAllMessage: 'Are you sure you want to clear all fields?',
      clear: 'Clear',
      close: 'Close',
      content: 'Content',
      copy: 'Copy To Clipboard',
      copyButton: '&#43;',
      copyButtonTooltip: 'Copy',
      dateField: 'Date Field',
      description: 'Help Text',
      descriptionField: 'Description',
      devMode: 'Developer Mode',
      editNames: 'Edit Names',
      editorTitle: 'Form Elements',
      editXML: 'Edit XML',
      enableOther: 'Enable &quot;Other&quot;',
      enableOtherMsg: 'Let users to enter an unlisted option',
      fieldNonEditable: 'This field cannot be edited.',
      fieldRemoveWarning: 'Are you sure you want to remove this field?',
      file: 'File Upload',
      fileUpload: 'File Upload',
      fileUploadInTab: 'File Upload in Tab',
      formUpdated: 'Form Updated',
      getStarted: 'Drag a field from the right to this area',
      header: 'Header',
      split: 'Split',
      hide: 'Edit',
      hidden: 'Hidden Input',
      inline: 'Inline',
      inlineDesc: 'Display {type} inline',
      label: 'Label',
      labelEmpty: 'Field Label cannot be empty',
      limitRole: 'Limit access to one or more of the following roles:',
      mandatory: 'Mandatory',
      maxlength: 'Max Length',
      minOptionMessage: 'This field requires a minimum of 2 options',
      minSelectionRequired: 'Minimum {min} selections required',
      multipleFiles: 'Multiple Files',
      name: 'Name',
      no: 'No',
      noFieldsToClear: 'There are no fields to clear',
      number: 'Number',
      money: 'Money',
      off: 'Off',
      on: 'On',
      option: 'Option',
      options: 'Options',
      optional: 'optional',
      optionLabelPlaceholder: 'Label',
      optionValuePlaceholder: 'Value',
      optionEmpty: 'Option value required',
      other: 'Other',
      paragraph: 'Paragraph',
      placeholder: 'Placeholder',
      'placeholder.value': 'Value',
      'placeholder.label': 'Label',
      'placeholder.text': '',
      'placeholder.textarea': '',
      'placeholder.email': 'Enter you email',
      'placeholder.placeholder': '',
      'placeholder.className': 'space separated classes',
      'placeholder.password': 'Enter your password',
      preview: 'Preview',
      radioGroup: 'Radio Group',
      radio: 'Radio',
      removeMessage: 'Remove Element',
      removeOption: 'Remove Option',
      remove: '&#215;',
      required: 'Required',
      richText: 'Rich Text Editor',
      roles: 'Access',
      rows: 'Rows',
      save: 'Save',
      selectOptions: 'Options',
      select: 'Select',
      selectColor: 'Select Color',
      selectionsMessage: 'Allow Multiple Selections',
      size: 'Size',
      'size.xs': 'Extra Small',
      'size.sm': 'Small',
      'size.m': 'Default',
      'size.lg': 'Large',
      style: 'Style',
      'styles.btn.default': 'Default',
      'styles.btn.danger': 'Danger',
      'styles.btn.info': 'Info',
      'styles.btn.primary': 'Primary',
      'styles.btn.success': 'Success',
      'styles.btn.warning': 'Warning',
      subtype: 'Type',
      text: 'Text Field',
      textArea: 'Text Area',
      toggle: 'Toggle',
      warning: 'Warning!',
      value: 'Value',
      viewJSON: '{  }',
      viewXML: '&lt;/&gt;',
      yes: 'Yes',
      flipswitch: 'Flip Switch',
      psbi: 'User Id',
      psbm: 'Email',
      psbn: 'User Name',
      bpid: 'Process Definition',
      'datetime-local': 'datetime',
      password: 'password'
    }

  },
}

export const config = {}
